// lint.mjs — CORE join-manifest integrity lint + burndown sweep
// (FRAMEWORK_DESIGN §4.4a + §9.1 + the adopted CRITIQUE Finding-4 content check).
//
// Three integrity checks per join row:
//   1. DERIVE  — cmpCapture is DERIVED from stateId (config.captureDeriveRule); a
//      row that hardcodes a different capture FAILS, so a crossed row is
//      structurally impossible, not merely lint-able.
//   2. ORPHAN  — the derived capture exists on disk (forward), and (reverse, the
//      §9.4 REMOVE safety net) every on-disk capture in a module maps to either
//      an authored frame, a backfill-queue slot, or a flagged stale orphan.
//   3. PIN     — designContentHash 'auto' is stamped from the live render's
//      pull-manifest; a pinned hash that drifts FAILS (§2.3 revision pinning).
//
// Plus the BURNDOWN sweep (the Forced-Decision-#1 visible burndown): per module,
// coverage% of design frames over the live inventory, the backfill queue
// (captured-but-no-frame), stale orphan PNGs (basename not in inventory), and
// inventory states with no capture. Generated from the LIVE on-disk inventory +
// captures — never a memorized constant (the 279→251 drift is the argument).

import path from 'node:path';
import { existsSync, readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { deriveCapture } from './config.mjs';

export function lint(cfg, opts = {}) {
  const findings = [];
  const ok = [];
  const outDir = opts.outDir || path.join(cfg.cacheDir, 'out');
  const manifest = cfg.manifest;

  const moduleById = new Map(cfg.modules.map((m) => [m.id, m]));

  // A configured-but-absent join-manifest must not make lint vacuously pass over
  // zero rows — warn loudly (it's generated by `pull --write-manifest`).
  if (cfg.manifestPresent === false) {
    findings.push({ row: '(join-manifest)', kind: 'MANIFEST_FILE_ABSENT', detail: `join-manifest configured at ${cfg.manifestPath} but the file does not exist — run \`pull --write-manifest\` to generate it` });
  } else if ((manifest.rows || []).length === 0) {
    ok.push('(join-manifest present but empty — run `pull --write-manifest` to populate rows from the live frames)');
  }

  for (const row of manifest.rows) {
    const tag = `${row.frameId || row.stateId} -> ${row.stateId}`;
    const mod = moduleById.get(row.module) || { id: row.module };
    const derivedAbs = deriveCapture(cfg, row.stateId, mod);
    const derivedRel = path.relative(cfg.cmpScreenshotRoot, derivedAbs);

    // (1) DERIVE / miswire check.
    if (row.cmpCapture && row.cmpCapture !== 'DERIVED' && row.cmpCapture !== derivedRel && row.cmpCapture !== derivedAbs) {
      findings.push({ row: tag, kind: 'MISWIRED_CAPTURE', detail: `row hardcodes cmpCapture="${row.cmpCapture}" but stateId derives "${derivedRel}"` });
    } else {
      ok.push(`${tag}: capture DERIVED -> ${derivedRel} (miswire structurally impossible)`);
    }

    // (2) ORPHAN forward: derived capture must exist (or be a known backfill slot).
    if (!existsSync(derivedAbs)) {
      findings.push({ row: tag, kind: 'DESIGN_STATE_WITHOUT_CAPTURE', detail: `no CMP capture at ${derivedRel} (expected during the backfill valley if the Compose state isn't built yet)`, severity: 'info' });
    } else {
      ok.push(`${tag}: CMP capture exists (${derivedRel})`);
    }

    // (3) PIN: stamp/verify designContentHash vs the live render pull-manifest.
    // Never pin a hash from a render that FAILED its own gate — render.mjs writes
    // the manifest unconditionally, so a failed render still leaves one on disk.
    const pm = path.join(outDir, `${row.stateId}.pull-manifest.json`);
    if (!existsSync(pm)) {
      // No render yet — informational, not a failure (render is a separate step).
      ok.push(`${tag}: (no render yet — run \`render ${row.stateId}\` to stamp the content hash)`);
    } else {
      const manifest = JSON.parse(readFileSync(pm, 'utf8'));
      const liveHash = manifest.sourceContentHash;
      const renderPassed = manifest.renderOk === true; // older manifests w/o the field count as not-passed
      if (manifest.renderOk !== undefined && !renderPassed) {
        findings.push({ row: tag, kind: 'STAMP_FROM_FAILED_RENDER', detail: `render did not pass its gate (${(manifest.renderReasons || []).join(', ') || 'unknown'}); refusing to pin/verify its hash` });
      } else if (!row.designContentHash || row.designContentHash === 'auto') {
        if (opts.stamp !== false) { row.designContentHash = liveHash; ok.push(`${tag}: designContentHash STAMPED ${liveHash.slice(0, 23)}…`); }
      } else if (row.designContentHash !== liveHash) {
        findings.push({ row: tag, kind: 'CONTENT_HASH_DRIFT', detail: `pinned ${row.designContentHash.slice(0, 23)}… != live ${liveHash.slice(0, 23)}… — frame was re-authored; re-verify` });
      } else {
        ok.push(`${tag}: designContentHash verified (no drift)`);
      }
    }
  }

  // ── Reverse-orphan / BURNDOWN sweep, per module ──
  const inventory = cfg.inventoryPath && existsSync(cfg.inventoryPath)
    ? readFileSync(cfg.inventoryPath, 'utf8').split('\n').map((s) => s.trim()).filter(Boolean)
    : null;

  if (opts.failOnBackfill && !inventory) {
    findings.push({ row: '(inventory)', kind: 'BACKFILL_GATE_NO_INVENTORY', severity: 'info', detail: `--fail-on-backfill requires a state inventory (config.inventoryPath) — enrollment is the per-state opt-in; the flag is ignored without one` });
  }

  const burndown = [];
  for (const mod of cfg.modules) {
    const captureDirAbs = mod.captureDir
      ? path.resolve(cfg.cmpScreenshotRoot, mod.captureDir)
      : cfg.cmpScreenshotRoot;
    const captures = existsSync(captureDirAbs)
      ? readdirSync(captureDirAbs).filter((f) => f.endsWith('.png') && f.startsWith(mod.statePrefix)).map((f) => f.replace(/\.png$/, ''))
      : [];
    const capturedSet = new Set(captures);
    const claimed = new Set(manifest.rows.filter((r) => r.module === mod.id).map((r) => r.stateId));
    const modInventory = inventory ? inventory.filter((id) => id.startsWith(mod.statePrefix)) : null;
    const invSet = modInventory ? new Set(modInventory) : null;

    const backfillQueue = captures.filter((id) => (!invSet || invSet.has(id)) && !claimed.has(id));
    const orphanPngs = invSet ? captures.filter((id) => !invSet.has(id)) : [];
    const inventoryNotCaptured = modInventory ? modInventory.filter((id) => !capturedSet.has(id)) : [];
    // Frames authored beyond the inventory (e.g. CMP-real states the prototype
    // enumeration never had — the reconcile-inventory-against-CMP signal). These
    // get their own bucket; they must NOT inflate coverage past 100%.
    const framesNotInInventory = invSet ? [...claimed].filter((id) => !invSet.has(id)) : [];
    // Coverage = authored frames that ARE in the inventory, over the inventory.
    const claimedInInventory = invSet ? [...claimed].filter((id) => invSet.has(id)) : [...claimed];
    const denom = modInventory
      ? modInventory.length
      : (captures.length + [...claimed].filter((id) => !capturedSet.has(id)).length);
    const numer = modInventory ? claimedInInventory.length : [...claimed].length;

    burndown.push({
      module: mod.id,
      inventoryStates: modInventory ? modInventory.length : null,
      cmpCaptures: captures.length,
      designFramesAuthored: [...claimed],
      coveragePct: denom ? Math.min(100, Math.round((numer / denom) * 100)) : 0,
      backfillQueue,
      orphanPngsNotInInventory: orphanPngs,
      inventoryNotYetCaptured: inventoryNotCaptured,
      framesNotInInventory,
    });

    // --fail-on-backfill: promote captured-but-no-frame (inventory-enrolled)
    // states from informational burndown to REAL findings. This is the
    // mechanical merge gate for the imported-reference (screenshot) flow: an
    // implementation may ship a capture before its design frame exists, but a
    // state must not REMAIN frame-less — wire this flag into CI to hold the
    // design-SoT boundary. Only inventory-enrolled states gate (enrollment is
    // the explicit opt-in; un-enrolled captures stay in orphanPngs).
    if (opts.failOnBackfill && invSet && backfillQueue.length) {
      for (const id of backfillQueue) {
        findings.push({ row: `${mod.id}/${id}`, kind: 'BACKFILL_REQUIRED', detail: `capture exists but no design frame — author/backfill the frame (route-B closes with a frame authored from the shipped implementation) or remove the state from the inventory` });
      }
    }
  }

  // Persist the (possibly hash-stamped) manifest + a report.
  if (opts.stamp !== false) writeFileSync(cfg.manifestPath, JSON.stringify(manifest, null, 2));
  mkdirSync(outDir, { recursive: true });
  const report = { pass: findings.filter((f) => f.severity !== 'info').length === 0, checks: ok, findings, burndown };
  writeFileSync(path.join(outDir, 'join-lint-report.json'), JSON.stringify(report, null, 2));
  return report;
}

export function printLintReport(report) {
  console.log(`JOIN-LINT ${report.pass ? 'PASS ✓' : 'FAIL ✗'}`);
  report.checks.forEach((l) => console.log('  ok  ' + l));
  report.findings.forEach((f) => console.log(`  ${f.severity === 'info' ? '··' : '!!'}  ${f.kind}: ${f.row} — ${f.detail}`));
  for (const b of report.burndown) {
    const inv = b.inventoryStates == null ? '(no inventory)' : `${b.inventoryStates} inventory states`;
    console.log(`\nBURNDOWN [${b.module}] — ${inv}; ${b.cmpCaptures} CMP captures on disk`);
    console.log(`  covered: ${b.designFramesAuthored.length} design frames (${b.coveragePct}%)`);
    console.log(`  backfill queue (captured, no frame): ${b.backfillQueue.length}${b.backfillQueue.length ? '  e.g. ' + b.backfillQueue.slice(0, 6).join(', ') : ''}`);
    if (b.orphanPngsNotInInventory.length) console.log(`  stale orphan PNGs (not in inventory): ${b.orphanPngsNotInInventory.length} -> ${b.orphanPngsNotInInventory.join(', ')}`);
    if (b.inventoryNotYetCaptured.length) console.log(`  inventory states with no CMP capture: ${b.inventoryNotYetCaptured.length}  e.g. ${b.inventoryNotYetCaptured.slice(0, 6).join(', ')}`);
    if (b.framesNotInInventory && b.framesNotInInventory.length) console.log(`  frames authored beyond inventory (reconcile inventory↑): ${b.framesNotInInventory.length} -> ${b.framesNotInInventory.join(', ')}`);
  }
}
